name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: fedora:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install host dependencies
        run: |
          dnf -y --setopt=install_weak_deps=False install git java-11-openjdk-devel which

      - name: Check out
        uses: actions/checkout@v3

      - name: Test
        run: |
          readonly user="$(whoami)"
          echo "Current user is: $user"
          echo "Passwd is: $(getent passwd $user)"
          echo "HOME environment variable is: $HOME"
          echo "System.getProperty("user.home") is: $(jshell -q < <(echo 'System.getProperty("user.home")'))"
          echo "os.homedir() is: $(/__e/node16/bin/node -e 'console.log(require("os").homedir())')"

      - name: Run Gradle
        uses: gradle/gradle-build-action@v2
        with:
            arguments: help
